on:
  push:

name: publish-pgai-vectorizer-worker-0.2.0

jobs:
  release-docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: timescale/pgai-vectorizer-worker
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ORG_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.ORG_DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:projects/pgai"
          push: true
          tags: timescale/pgai-vectorizer-worker:v0.2.0
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
